name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0

flutter:
  uses-material-design: true
flutter_launcher_icons:
  image_path: "my_own_app_icon.png"
  android: true
