name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate android project files
        run: flutter create . --platforms=android
      - name: Я Коплю
        run: sed -i 's/android:label="[^"]*"/android:label="Я Коплю"/g' android/app/src/main/AndroidManifest.xml
      - name: Fix compileSdk for all dependencies
        run: |
          echo "subprojects { afterEvaluate { project -> if (project.hasProperty('android')) { project.android { compileSdkVersion 36 } } } }" >> android/build.gradle

      - name: Install dependencies
        run: flutter pub get
      - name: Install launcher icons package
        run: flutter pub add flutter_launcher_icons

      - name: Generate app icon
        run: dart run flutter_launcher_icons:main
      
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK via Gradle
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
